clc;
clear;
close all;
%% ------------------------------ Setting ------------------------------ %%
Version = 'Sample_02';
Case    = 'Illustrative';
UC_Mode = 'C';
Cost_SYS_ACT_PPO = 419890;
% 'C': Closed-Loop Predict-and-Optimize
%% ------------------------------- Path -------------------------------- %%
Ini_Path = which('Location_CPO_v7.m');
Ini_Size = size('Location_CPO_v7.m', 2);
Link = Ini_Path(end - Ini_Size);
Path_Data = strcat(Ini_Path(1:end - Ini_Size - 1), Link, 'Database');
Path_Case = strcat(Ini_Path(1:end - Ini_Size - 1), Link, 'Case_Studies');
Path_Case = strcat(Path_Case, Link, Case);
Date_Dispatch = '16-Feb-2020';
Error = [0.7:0.005:1.3]' - 1;
Num_Sample = size(Error, 1);
%
%% ---------------------------- Prepare Box ---------------------------- %%
% UC
Var_UC_I     = cell(Num_Sample, 1);
Var_UC_I_SU  = cell(Num_Sample, 1);
Var_UC_I_SD  = cell(Num_Sample, 1);
Var_UC_I_RC  = cell(Num_Sample, 1);
Var_UC_P     = cell(Num_Sample, 1);
Var_UC_W     = cell(Num_Sample, 1);
Var_UC_R_H   = cell(Num_Sample, 1);
Var_UC_R_C   = cell(Num_Sample, 1);

Cost_UC_SU   = zeros(Num_Sample, 1);
Cost_UC_NL   = zeros(Num_Sample, 1);
Cost_UC_P    = zeros(Num_Sample, 1);
Cost_UC_RH   = zeros(Num_Sample, 1);
Cost_UC_RC   = zeros(Num_Sample, 1);
Cost_UC_ACT  = zeros(Num_Sample, 1);
Cost_SYS_EXP = zeros(Num_Sample, 1);

RES_Pre_Farm = cell(Num_Sample, 1);
RES_Pre_SUM  = cell(Num_Sample, 1);
R_H_Req_Dis  = cell(Num_Sample, 1);
R_C_Req_Dis  = cell(Num_Sample, 1);
% ED
Var_ED_I     = cell(Num_Sample, 1);
Var_ED_I_SU  = cell(Num_Sample, 1);
Var_ED_I_SD  = cell(Num_Sample, 1);
Var_ED_P     = cell(Num_Sample, 1);
Var_ED_W     = cell(Num_Sample, 1);
Var_ED_S1    = cell(Num_Sample, 1);
Var_ED_S2    = cell(Num_Sample, 1);
Var_ED_S3    = cell(Num_Sample, 1);
Var_ED_S4    = cell(Num_Sample, 1);
Cost_ED_SU   = zeros(Num_Sample, 1);
Cost_ED_NL   = zeros(Num_Sample, 1);
Cost_ED_P    = zeros(Num_Sample, 1);
Cost_ED_S1   = zeros(Num_Sample, 1);
Cost_ED_S2   = zeros(Num_Sample, 1);
Cost_ED_S3   = zeros(Num_Sample, 1);
Cost_ED_S4   = zeros(Num_Sample, 1);
Cost_ED_ACT  = zeros(Num_Sample, 1);
Cost_SYS_ACT = zeros(Num_Sample, 1);

Rate_RES   = cell(Num_Sample, 1);
Rate_RH    = cell(Num_Sample, 1);
Rate_RH_Up = cell(Num_Sample, 1);
Rate_RH_Dn = cell(Num_Sample, 1);
Rate_RC    = cell(Num_Sample, 1);

Rate_RES_AVR   = zeros(Num_Sample, 1);
Rate_RH_AVR    = zeros(Num_Sample, 1);
Rate_RH_Up_AVR = zeros(Num_Sample, 1);
Rate_RH_Dn_AVR = zeros(Num_Sample, 1);
Rate_RC_AVR    = zeros(Num_Sample, 1);

PE_MAE  = zeros(Num_Sample, 1);
PE_MAPE = zeros(Num_Sample, 1);
PE_MOPE = zeros(Num_Sample, 1);
PE_MUPE = zeros(Num_Sample, 1);
%
%% ------------------------------ Testing ------------------------------ %%
OVar_Phi_RES = ones(24, 5);
OVar_Phi_R_H = 0.15*ones(24, 1);
OVar_Phi_R_C = 0.15*ones(24, 1);
for Sample = 1:Num_Sample    
    disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
    disp(['Sample ', num2str(Sample)]);
    disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
    %
    [Var_UC_I{Sample},...
        Var_UC_I_SU{Sample},...
        Var_UC_I_SD{Sample},...
        Var_UC_I_RC{Sample},...
        Var_UC_P{Sample},...
        Var_UC_W{Sample},...
        Var_UC_R_H{Sample},...
        Var_UC_R_C{Sample},...
        Cost_UC_SU(Sample),...
        Cost_UC_NL(Sample),...
        Cost_UC_P(Sample),...
        Cost_UC_RH(Sample),...
        Cost_UC_RC(Sample),...
        Cost_UC_ACT(Sample),...
        Cost_SYS_EXP(Sample),...
        RES_Pre_Farm{Sample},...
        RES_Pre_SUM{Sample},...
        R_H_Req_Dis{Sample},...
        R_C_Req_Dis{Sample}]...
        = UC_Auto_Sample_v7(UC_Mode,...
        Date_Dispatch,...
        OVar_Phi_RES + Error(Sample),...
        OVar_Phi_R_H,...
        OVar_Phi_R_C,...
        Link,...
        Path_Data);
    %
    [Var_ED_I{Sample},...
        Var_ED_I_SU{Sample},...
        Var_ED_I_SD{Sample},...
        Var_ED_P{Sample},...
        Var_ED_W{Sample},...
        Var_ED_S1{Sample},...
        Var_ED_S2{Sample},...
        Var_ED_S3{Sample},...
        Var_ED_S4{Sample},...
        Cost_ED_SU(Sample),...
        Cost_ED_NL(Sample),...
        Cost_ED_P(Sample),...
        Cost_ED_S1(Sample),...
        Cost_ED_S2(Sample),...
        Cost_ED_S3(Sample),...
        Cost_ED_S4(Sample),...
        Cost_ED_ACT(Sample),...
        Cost_SYS_ACT(Sample),...
        Rate_RES{Sample},...
        Rate_RH{Sample},...
        Rate_RH_Up{Sample},...
        Rate_RH_Dn{Sample},...
        Rate_RC{Sample},...
        Rate_RES_AVR(Sample),...
        Rate_RH_AVR(Sample),...
        Rate_RH_Up_AVR(Sample),...
        Rate_RH_Dn_AVR(Sample),...
        Rate_RC_AVR(Sample),...
        PE_MAE(Sample),...
        PE_MAPE(Sample),...
        PE_MOPE(Sample),...
        PE_MUPE(Sample)]...
        = ED_Auto_v7(Date_Dispatch,...
        Var_UC_I{Sample},...
        Var_UC_P{Sample},...
        Var_UC_R_H{Sample},...
        Var_UC_R_C{Sample},...
        Cost_UC_ACT(Sample),...
        RES_Pre_Farm{Sample},...
        RES_Pre_SUM{Sample},...
        R_H_Req_Dis{Sample},...
        R_C_Req_Dis{Sample},...
        Link,...
        Path_Data);
    %
    if Cost_ED_ACT(Sample) <= 1
        [Var_ED_I{Sample},...
            Var_ED_I_SU{Sample},...
            Var_ED_I_SD{Sample},...
            Var_ED_P{Sample},...
            Var_ED_W{Sample},...
            Var_ED_S1{Sample},...
            Var_ED_S2{Sample},...
            Var_ED_S3{Sample},...
            Var_ED_S4{Sample},...
            Cost_ED_SU(Sample),...
            Cost_ED_NL(Sample),...
            Cost_ED_P(Sample),...
            Cost_ED_S1(Sample),...
            Cost_ED_S2(Sample),...
            Cost_ED_S3(Sample),...
            Cost_ED_S4(Sample),...
            Cost_ED_ACT(Sample),...
            Cost_SYS_ACT(Sample),...
            Rate_RES{Sample},...
            Rate_RH{Sample},...
            Rate_RH_Up{Sample},...
            Rate_RH_Dn{Sample},...
            Rate_RC{Sample},...
            Rate_RES_AVR(Sample),...
            Rate_RH_AVR(Sample),...
            Rate_RH_Up_AVR(Sample),...
            Rate_RH_Dn_AVR(Sample),...
            Rate_RC_AVR(Sample),...
            PE_MAE(Sample),...
            PE_MAPE(Sample),...
            PE_MOPE(Sample),...
            PE_MUPE(Sample)]...
            = ED_Auto_S1_v7(Date_Dispatch,...
            Var_UC_I{Sample},...
            Var_UC_P{Sample},...
            Var_UC_R_H{Sample},...
            Var_UC_R_C{Sample},...
            Cost_UC_ACT(Sample),...
            RES_Pre_Farm{Sample},...
            RES_Pre_SUM{Sample},...
            R_H_Req_Dis{Sample},...
            R_C_Req_Dis{Sample},...
            Link,...
            Path_Data);
    end
    %
    if Cost_ED_ACT(Sample) <= 1
        [Var_ED_I{Sample},...
            Var_ED_I_SU{Sample},...
            Var_ED_I_SD{Sample},...
            Var_ED_P{Sample},...
            Var_ED_W{Sample},...
            Var_ED_S1{Sample},...
            Var_ED_S2{Sample},...
            Var_ED_S3{Sample},...
            Var_ED_S4{Sample},...
            Cost_ED_SU(Sample),...
            Cost_ED_NL(Sample),...
            Cost_ED_P(Sample),...
            Cost_ED_S1(Sample),...
            Cost_ED_S2(Sample),...
            Cost_ED_S3(Sample),...
            Cost_ED_S4(Sample),...
            Cost_ED_ACT(Sample),...
            Cost_SYS_ACT(Sample),...
            Rate_RES{Sample},...
            Rate_RH{Sample},...
            Rate_RH_Up{Sample},...
            Rate_RH_Dn{Sample},...
            Rate_RC{Sample},...
            Rate_RES_AVR(Sample),...
            Rate_RH_AVR(Sample),...
            Rate_RH_Up_AVR(Sample),...
            Rate_RH_Dn_AVR(Sample),...
            Rate_RC_AVR(Sample),...
            PE_MAE(Sample),...
            PE_MAPE(Sample),...
            PE_MOPE(Sample),...
            PE_MUPE(Sample)]...
            = ED_Auto_S2_v7(Date_Dispatch,...
            Var_UC_I{Sample},...
            Var_UC_P{Sample},...
            Var_UC_R_H{Sample},...
            Var_UC_R_C{Sample},...
            Cost_UC_ACT(Sample),...
            RES_Pre_Farm{Sample},...
            RES_Pre_SUM{Sample},...
            R_H_Req_Dis{Sample},...
            R_C_Req_Dis{Sample},...
            Link,...
            Path_Data);
    end
    %
    if Cost_ED_ACT(Sample) <= 1
        [Var_ED_I{Sample},...
            Var_ED_I_SU{Sample},...
            Var_ED_I_SD{Sample},...
            Var_ED_P{Sample},...
            Var_ED_W{Sample},...
            Var_ED_S1{Sample},...
            Var_ED_S2{Sample},...
            Var_ED_S3{Sample},...
            Var_ED_S4{Sample},...
            Cost_ED_SU(Sample),...
            Cost_ED_NL(Sample),...
            Cost_ED_P(Sample),...
            Cost_ED_S1(Sample),...
            Cost_ED_S2(Sample),...
            Cost_ED_S3(Sample),...
            Cost_ED_S4(Sample),...
            Cost_ED_ACT(Sample),...
            Cost_SYS_ACT(Sample),...
            Rate_RES{Sample},...
            Rate_RH{Sample},...
            Rate_RH_Up{Sample},...
            Rate_RH_Dn{Sample},...
            Rate_RC{Sample},...
            Rate_RES_AVR(Sample),...
            Rate_RH_AVR(Sample),...
            Rate_RH_Up_AVR(Sample),...
            Rate_RH_Dn_AVR(Sample),...
            Rate_RC_AVR(Sample),...
            PE_MAE(Sample),...
            PE_MAPE(Sample),...
            PE_MOPE(Sample),...
            PE_MUPE(Sample)]...
            = ED_Auto_SS_v7(Date_Dispatch,...
            Var_UC_I{Sample},...
            Var_UC_P{Sample},...
            Var_UC_R_H{Sample},...
            Var_UC_R_C{Sample},...
            Cost_UC_ACT(Sample),...
            RES_Pre_Farm{Sample},...
            RES_Pre_SUM{Sample},...
            R_H_Req_Dis{Sample},...
            R_C_Req_Dis{Sample},...
            Link,...
            Path_Data);
    end
end
Cost_Loss = (Cost_SYS_ACT - Cost_SYS_ACT_PPO)/Cost_SYS_ACT_PPO;
A_Data = [Error Cost_Loss];
save(strcat(Path_Case, Link, Version, '.mat'));

