clc;
clear;
close all;
%% ------------------------------ Setting ------------------------------ %%
Num_Scen      = 3000;
%
%% ------------------------------- Path -------------------------------- %%
Ini_Path  = which('Location_CPO_v7.m');
Ini_Size  = size('Location_CPO_v7.m', 2);
Link      = Ini_Path(end - Ini_Size);
Path_Data = strcat(Ini_Path(1:end - Ini_Size - 1), Link, 'Database');
%
%% ------------------------------ Loading ------------------------------ %%
Num_Season    = 4;
Date_Dispatch = '2020-03-06';
Peak_Day_List = [65;224;335;345];
[Num_Gen,...
 Num_Branch,...
 Num_Bus,...
 Num_City,...
 Num_Hour,...
 Num_RES,...
 Gen_Capacity,...
 Gen_Price,...
 Branch,...
 Load_Gro_SUM_All_ACT,...
 Load_Gro_SUM_All_DAF,...
 Load_Gro_SUM_Dis_ACT,...
 Load_Gro_SUM_Dis_DAF, Load_Gro_SUM_Dis_DAF_UB, Load_Gro_SUM_Dis_DAF_LB,...
 Load_Net_SUM_All_ACT,...
 Load_Net_SUM_All_DAF,...
 Load_Net_SUM_Dis_ACT,...
 Load_Net_SUM_Dis_DAF,...
 Load_City_All_ACT,...
 Load_City_All_DAF,...
 Load_City_Dis_ACT,...
 Load_City_Dis_DAF,...
 RES_SUM_All_ACT,...
 RES_SUM_All_DAF, RES_SUM_All_DAF_UB, RES_SUM_All_DAF_LB,...
 RES_SUM_Dis_ACT,...
 RES_SUM_Dis_DAF, RES_SUM_Dis_DAF_UB, RES_SUM_Dis_DAF_LB,...
 RES_Farm_All_ACT,...
 RES_Farm_All_DAF, RES_Farm_All_DAF_UB, RES_Farm_All_DAF_LB,...
 RES_Farm_Dis_ACT,...
 RES_Farm_Dis_DAF, RES_Farm_Dis_DAF_UB, RES_Farm_Dis_DAF_LB,...
 R_Sys_Req_All,...
 R_Sys_Req_Dis,...
 R_H_Req_All,...
 R_H_Req_Dis,...
 R_C_Req_All,...
 R_C_Req_Dis,...
 PTDF_Gen,...
 PTDF_City,...
 PTDF_RES,...
 GS_Price,...
 LS_Price,...
 BS_Price,...
 Date_All_List,...
 Day, Pre_W_UB, Pre_W_LB,...
 Unit_Quick,...
 Unit_Thermal] = Database_CPO_v7(Date_Dispatch, Link, Path_Data);
%
Load_Gro_SUM_All_DAF_UB_Norm = readmatrix(strcat(Path_Data, Link, 'Load_Gro_SUM_DAF_UB.csv')); 
Load_Gro_SUM_All_DAF_LB_Norm = readmatrix(strcat(Path_Data, Link, 'Load_Gro_SUM_DAF_LB.csv'));

Load_Gro_SUM_All_DAF_UB = Load_Gro_SUM_All_DAF_UB_Norm.*Load_Gro_SUM_All_DAF;
Load_Gro_SUM_All_DAF_LB = Load_Gro_SUM_All_DAF_LB_Norm.*Load_Gro_SUM_All_DAF;
%
%% -------------------------------- LHS -------------------------------- %%
for Season = 1:Num_Season
    Day_Dispatch = Peak_Day_List(Season);
    disp(Day_Dispatch);
    % Range
    Range_Load_Gro_DAF{Day_Dispatch, 1} = Load_Gro_SUM_All_DAF_UB(:, Day_Dispatch) - Load_Gro_SUM_All_DAF_LB(:, Day_Dispatch);
    Range_RES_Farm_All_DAF{Day_Dispatch,1} = RES_Farm_All_DAF_UB{Day_Dispatch} - RES_Farm_All_DAF_LB{Day_Dispatch};
    % Load
    for Scen = 1:Num_Scen
        Scen_Load{Day_Dispatch, 1}(:, Scen) = Load_Gro_SUM_All_DAF_LB(:, Day_Dispatch)...
                                                            + lhsdesign(Num_Hour, 1).*Range_Load_Gro_DAF{Day_Dispatch};
        % RES
        Scen_RES_Farm_All_DAF{Day_Dispatch,1}{Scen} = RES_Farm_All_DAF_LB{Day_Dispatch}...
                                                    + lhsdesign(Num_Hour, Num_RES).*Range_RES_Farm_All_DAF{Day_Dispatch};
        %
        Scen_RES_01{Day_Dispatch,1}(:, Scen) = Scen_RES_Farm_All_DAF{Day_Dispatch}{Scen}(:, 1);
        Scen_RES_02{Day_Dispatch,1}(:, Scen) = Scen_RES_Farm_All_DAF{Day_Dispatch}{Scen}(:, 2);
        Scen_RES_03{Day_Dispatch,1}(:, Scen) = Scen_RES_Farm_All_DAF{Day_Dispatch}{Scen}(:, 3);
        Scen_RES_04{Day_Dispatch,1}(:, Scen) = Scen_RES_Farm_All_DAF{Day_Dispatch}{Scen}(:, 4);
        Scen_RES_05{Day_Dispatch,1}(:, Scen) = Scen_RES_Farm_All_DAF{Day_Dispatch}{Scen}(:, 5);
    end
end